In [2]:
#importar as bibliotecas
from numpy import pi 
from numpy import sys
import numpy as np

In [3]:
print('Versão atual do numpy', np.__version__)

Versão atual do numpy 1.18.5


In [4]:
B = np.arange(3)
B

array([0, 1, 2])

In [5]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [6]:
#Retorna a raiz quadrada
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [8]:
C = np.array([2.,-1., 4.])
C

array([ 2., -1.,  4.])

In [9]:
np.add(B,C)

array([2., 0., 6.])